### PR TITLE
Auto-play if Animation.hasScripting is true

### PR DESCRIPTION
**Pull request by shamansir**

### CODE REVIEW

**Comment by mcm69** [comment]
Can you explain me the reasoning behind this?

**Comment by shamansir** [comment]
We do interactivity now. So projects with event handlers should have no controls and auto-play when published (in `publish.html` page) or in ether case controls will capture all the mouse events. `.hasScripting` (the previous name for _interactivity_ :) ) flag is set with Animatron Importer when project like this was received.

In the best case, `autoPlay` and `controlsEnabled` options should be set in `publish.html`/`.js` for these projects (and no weird assumptions should be done in the importer), so controls will be disabled from the start, before the loading process, in the proper way. But it has to be done at the server side, so we decided to leave this flag here temporary.

**Comment by mcm69** [comment]
> So projects with event handlers should have no controls and auto-play when published
can't say i like this

**Comment by shamansir** [comment]
Why not? :). If it's a banner or something interactive, it could be hard for user to click shapes inside. Or it's regarding auto-play? Auto-play is the result of disabled controls: user has no "Play" button, so unable to start "playing" the scene (which is infinite, by the way—it never stops).

**Comment by mcm69** [comment]
yeah, sounds reasonable now, thanks for the explanation

**Pull request merged**
