### PR TITLE
Enable analytics on production

### PR DESCRIPTION
**Pull request by RobertoUa**
@skavish @shamansir

### CODE REVIEW

**Comment by shamansir** [comment]
Is it ok to merge w/o @skavish review?

**Comment by RobertoUa** [comment]
let's wait for @skavish to merge this

**Comment by skavish** [comment]
will it work without analytics, i.e. if we don't have any analytics installed?

**Comment by RobertoUa** [comment]
What do mean by `analytics installed`?
If analytics server is down(or not available) nothing bad will happen.
If use player for adwords the whole `analytics.js` won't be included to the player.

**Pull request merged**
