### PR TITLE
added outline=none to all created canvases

### PR DESCRIPTION
**Pull request by skavish**

### CODE REVIEW

**Comment by skavish** [comment]
please review, we need it asap

**Comment by shamansir** [comment]
Actually I did it already: https://github.com/Animatron/player/blame/9fec84b0feab5cc77b40a60da7a1b01dafb56b5b/src/engine/dom-engine.js#L674.

Also, why `newCanvas` is better? it's quite easy to forget space between `new` and `Canvas` and break some staff, also there's `anm.createPlayer` and so on, so it's like common naming system for factory methods.

**Comment by shamansir** [comment]
Uh, got it, it's a wrap for overriding the style. I will cherry-pick the commit I've done instead, if you are not completely against it.

**Comment by shamansir** [comment]
Update: I merged your PR to `master` since I am not sure code there is ok with my version and your version is straight and safe. But my way is safe for `develop` version, so I'll leave it here and then rewrite the `master` with latest version.

**Pull request closed without merging**
