### PR TITLE
Avoid try catch

### PR DESCRIPTION
**Pull request by shamansir**
Several optimizations suggested by Chrome Profiler when tested with large numbers of objects, should highly improve performance:

* `try/catch` blocks were removed from render loop, the error system is based on events and passing the error to the subject before firing it now.
* excessive events like `X_DRAW` were removed, ability to handle `Player` events was removed from `Element` and `Animation` code, now only a subject of event may catch it's event, to avoid loops going too deep with no reason (keyboard/mouse events will still be passed to element's children if they were in bounds of element); the latter could cause errors with an audio/video, they rely on some Player events like `S_START`/`S_STOP`, so it _could be dangerous_;
* Excessive "safe" methods were removed because they used `try`/`catch` to handle errors;

Please **do not merge** until it will be safe to deploy.

### CODE REVIEW

**Comment by skavish** [comment]
can't wait to see it in action!

**Comment by mcm69** [comment]
how about we throw it on test and see what happens?

**Comment by shamansir** [comment]
Yeah, let's do it. Latest commit in develop is 2964e9bc18 for the records.

**Comment by mcm69** [comment]
@shamansir There are still issues, so please in the future announce you're about to merge a PR so I could at least take a quick look.

**Comment by shamansir** [comment]
@mcm69 

> how about we throw it on test and see what happens?

I suppose it means "to merge into `develop` and deploy", no? 'Cause `develop` should match player at test, and `master` should match player at production

**Comment by mcm69** [comment]
i meant 'deploy it on test and let someone take a look while keeping the PR open', i am sorry if I was unclear.

**Comment by mcm69** [comment]
in case we enforce the develop/test and prod/master rule, we'll need something like skunkworks website to test bleeding edge player there

**Pull request merged**
