### PR TITLE
Show Resource Loading Completeness

### PR DESCRIPTION
**Pull request by shamansir**
Draws a tiny 2px-line at the bottom of controls to show the completeness of resources loading process. 

For audio, it has the ability to monitor chunks, [this demo](http://jspro.brothercake.com/media-events/progress.html) and [this article](http://www.sitepoint.com/essential-audio-and-video-events-for-html5/) were used to find out how to do it. For images, it just reports when they are done loading. The total number of URLs requested is used as `1.0`, each file is then `1 / <number-of-urls>` part in the progress line. For audio files, this value is then divided into sub-parts.

Demo

(sorry, I was able to catch only the last moments of loading :) ).

Needs testing.

Also I ask to merge this just after the request, since it contains ResourceManager changes which should be considered by Yuri in his proposals and/or changes :). Code review fixes could be done with the next pull requests.

@alexeypegov @mcm69 please review.

### CODE REVIEW

**Comment by mcm69** [comment]
Please use the circle and draw loading progress there instead of introducing a new design element.

**Comment by shamansir** [comment]
There was a discussion somewhere between issues or chats where we all stated out that this should be a line like this, at the bottom, because circle doesn't work very well for this purpose, it's not easy for user to get what's actually happening.

**Comment by mcm69** [comment]
how can you not get a circle getting filed?
also, i'd vote for going along with Artem's design and add the percentage in the center.

**Comment by shamansir** [comment]
Ok, let's move it to Slack, I though everything was clear. We haven't the idea of filling circle though.

**Comment by alexeypegov** [comment]
personally, I think that loading progress should be similar to playing one

On Wednesday, February 11, 2015, Yuriy Opryshko <notifications@github.com>
wrote:

> Please use the circle and draw loading progress there instead of
> introducing a new design element.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Animatron/player/pull/270#issuecomment-73859044>.
>


-- 

--
PEGOV

**Pull request merged**
